[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
    
[[headers]]
  for = "/_astro/*"
  [headers.values]
    cache-control = '''
    max-age=365000000,
    public
    immutable'''